title: Michael Todd
description: An old-school blog focusing on statistics, ML and AI.
url: "https://michaeltodd.io"
baseurl: ""

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
author: Michael Todd
lang: en_US

# Excerpt settings
excerpt_separator: "\n\n"  # Auto-generate excerpts from first paragraph

# Include files
include:
  - _pages